root: true

parser: "@typescript-eslint/parser"

plugins:
  - wdio
  - "@typescript-eslint"

extends:
  - airbnb-base
  - plugin:wdio/recommended
  - plugin:@typescript-eslint/recommended
  - prettier

globals:
  assert: true
  expect: true

env:
  es6: true
  node: true

rules:
  global-require: "off"
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  new-cap:
    - "error"
    - newIsCap: true
      capIsNewExceptions:
        - "Given"
        - "When"
        - "Then"
  require-jsdoc:
    - "error"
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict: "off"
  valid-jsdoc:
    - "error"
    - requireReturn: false
      matchDescription: ".+"
  "@typescript-eslint/ban-ts-comment": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  import/no-unresolved: 0
  import/extensions: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
