"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const cucumber_1 = require("@cucumber/cucumber");
const clearInputField_1 = __importDefault(require("../support/action/clearInputField"));
const clickElement_1 = __importDefault(require("../support/action/clickElement"));
const closeLastOpenedWindow_1 = __importDefault(require("../support/action/closeLastOpenedWindow"));
const deleteCookies_1 = __importDefault(require("../support/action/deleteCookies"));
const dragElement_1 = __importDefault(require("../support/action/dragElement"));
const focusLastOpenedWindow_1 = __importDefault(require("../support/action/focusLastOpenedWindow"));
const handleModal_1 = __importDefault(require("../support/action/handleModal"));
const moveTo_1 = __importDefault(require("../support/action/moveTo"));
const pause_1 = __importDefault(require("../support/action/pause"));
const pressButton_1 = __importDefault(require("../support/action/pressButton"));
const scroll_1 = __importDefault(require("../support/action/scroll"));
const selectOption_1 = __importDefault(require("../support/action/selectOption"));
const selectOptionByIndex_1 = __importDefault(require("../support/action/selectOptionByIndex"));
const setCookie_1 = __importDefault(require("../support/action/setCookie"));
const setInputField_1 = __importDefault(require("../support/action/setInputField"));
const setPromptText_1 = __importDefault(require("../support/action/setPromptText"));
(0, cucumber_1.When)(/^I (click|doubleclick) on the (link|button|element) "([^"]*)?"$/, clickElement_1.default);
(0, cucumber_1.When)(/^I (add|set) "([^"]*)?" to the inputfield "([^"]*)?"$/, setInputField_1.default);
(0, cucumber_1.When)(/^I clear the inputfield "([^"]*)?"$/, clearInputField_1.default);
(0, cucumber_1.When)(/^I drag element "([^"]*)?" to element "([^"]*)?"$/, dragElement_1.default);
(0, cucumber_1.When)(/^I pause for (\d+)ms$/, pause_1.default);
(0, cucumber_1.When)(/^I set a cookie "([^"]*)?" with the content "([^"]*)?"$/, setCookie_1.default);
(0, cucumber_1.When)(/^I delete the cookie "([^"]*)?"$/, deleteCookies_1.default);
(0, cucumber_1.When)(/^I press "([^"]*)?"$/, pressButton_1.default);
(0, cucumber_1.When)(/^I (accept|dismiss) the (alertbox|confirmbox|prompt)$/, handleModal_1.default);
(0, cucumber_1.When)(/^I enter "([^"]*)?" into the prompt$/, setPromptText_1.default);
(0, cucumber_1.When)(/^I scroll to element "([^"]*)?"$/, scroll_1.default);
(0, cucumber_1.When)(/^I close the last opened (window|tab)$/, closeLastOpenedWindow_1.default);
(0, cucumber_1.When)(/^I focus the last opened (window|tab)$/, focusLastOpenedWindow_1.default);
(0, cucumber_1.When)(/^I select the (\d+)(st|nd|rd|th) option for element "([^"]*)?"$/, selectOptionByIndex_1.default);
(0, cucumber_1.When)(/^I select the option with the (name|value|text) "([^"]*)?" for element "([^"]*)?"$/, selectOption_1.default);
(0, cucumber_1.When)(/^I move to element "([^"]*)?"(?: with an offset of (\d+),(\d+))*$/, moveTo_1.default);
